profile: r2560x1440
cursorStepsCount: 1
cursorStepDurationSec: 0
logLevel: ERROR
numOfPagesToScrape: 1
resolution:
  r2560x1440:
    candleWidthPx: 10
    firstCandleCenterX: 300
    ohlcvScreenRegion:
      h: 15
      w: 515
      x: 325
      y: 125
    rsiScreenRegion:
      h: 17
      w: 45
      x: 430
      y: 1042
    calendarPickerCenterCoords:
      x: 2320
      y: 58
    calendarNextMonthButtonCenterCoords:
      x: 2386
      y: 91
    calendarFirstDayRegion:
      h: 22
      w: 28
      x: 2217
      y: 135
    bufferingStatusRegion:
      h: 17
      w: 75
      x: 80
      y: 30
    timeFieldInsideCoords:
      x: 2270
      y: 280
    calendarGoButtonCenterCoords:
      x: 2388
      y: 288