profile: r2560x1440
cursorStepsCount: 1
cursorStepDurationSec: 0
logLevel: ERROR
resolution:
  r2560x1440:
    candleWidthPx: 10
    firstCandleCenterX: 300
    ohlcvScreenRegion:
      h: 15
      w: 515
      x: 325
      y: 125
    rsiScreenRegion:
      h: 17
      w: 45
      x: 430
      y: 1042
