profile: r2560x1440
cursorStepsCount: 10000
cursorStepDurationSec: 0.01
logLevel: INFO
numOfPagesToScrape: 30
resolution:
  r2560x1440:
    candleWidthPx: 10
    firstCandleCenterX: 300
    ohlcvScreenRegion:
      h: 15
      w: 715
      x: 255
      y: 118
    rsiScreenRegion:
      h: 15
      w: 37
      x: 448
      y: 1185
    calendarPickerCenterCoords:
      x: 2320
      y: 58
    calendarNextMonthButtonCenterCoords:
      x: 2386
      y: 91
    calendarFirstDayRegion:
      h: 22
      w: 28
      x: 2217
      y: 135
    bufferingStatusRegion:
      h: 17
      w: 75
      x: 80
      y: 30
    timeFieldInsideCoords:
      x: 2270
      y: 280
    calendarGoButtonCenterCoords:
      x: 2388
      y: 288