profile: r2560x1440
resolution:
  r2560x1440:
    candleWidthPx: 10
    cursorStepDurationSec: 1
    cursorStepsCount: 10000
    firstCandleCenterX: 300
    ohlcvScreenRegion:
      h: 15
      w: 515
      x: 325
      y: 125
    rsiScreenRegion:
      h: 17
      w: 45
      x: 430
      y: 1042
