{
    'resolution': {
        '2560x1440': {
            'ohlcvScreenRegion': {
                'x': 325,
                'y': 125,
                'w': 515,
                'h': 15
            },
            'rsiScreenRegion': {
                'x': 430,
                'y': 1042,
                'w': 45,
                'h': 17
            }
        }
    }
}